kops_create_cluster_state: "s3://kubecluster-state-store.domain.com" 
kops_create_cluster_zones: "us-east-1a,us-east-1b,us-east-1c" 
kops_create_cluster_master_count: "1" 
kops_create_cluster_master_size: "t2.medium"
kops_create_cluster_node_count: "2"
kops_create_cluster_node_size: "t2.medium"
kops_create_cluster_name: "awskubecluster.k8s.local"
aws_region: "your_region" # Same as Terraform file terraform.tfvars
# Resources created by Terraform
terraform_project_path: "/boxdata/terraform" 
kubernetes_states_bucket: "kubecluster-state-store.domain.com"
dest_access_key: "/boxdata/terraform/kops_accesskey"
dest_secret_key: "/boxdata/terraform/kops_secretkey"
acm_ssl_data_file: "/tmp/acm_arn"
#################################
dns_base: "domain.com"
service_domain: "mediawiki.domain.com"
local_user: "vagrant"
local_user_home_dir: "/home/vagrant"
main_region: "your_region"
ssh_keys_dir: "/boxdata/terraform/ssh-keys"
sshkey_name: "kopsid_rsa"
## Kubernetes variables ##
dashboard_git_url: "https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta1/aio/deploy/recommended.yaml"
k8s_dashboard: "http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/login"
unhealthy_cluster_error: "kops update cluster"
kube_config_file: "~/.kube"
kops_files_dir: "/boxdata/kops-files"
proxy_process: "proxy"
kube_lb_svc: "mediawiki"
http_pod_port: "8080"
mysql_pod_port: "3306"
## Mediawiki app vars
mediawikidbhost: "mediawikidb"
mediawikidbname: "mediawdb"
mediadbwikiuser: "wikidbuser"
mediadbwikipass: "passwd123"
wikilogin: "wiki_user"
wikiloginpass: "wiki_user2020"
wikiloginemail: "wiki_user@wikidomain.com"
wikisitename: "MediaWiki"
